name: 'test deployment keys'

on:
  push:
    branches:
      - "master"
  workflow_dispatch:

jobs:
  plan:
    runs-on: ["kubernetes", "linux"]
    defaults:
      run:
        working-directory: ./terraform
    steps:
      - name: Terraform - checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: uptime
        run: |
          uptime
