name: Check drifts
on:
  schedule:
  - cron: '*/1 * * * *'

jobs:
  plan:
    runs-on: [ self-hosted ]
    defaults:
      run:
        working-directory: ./terraform
    steps:
      - name: Terraform - checkout
        uses: actions/checkout@v3

      - name: Use required terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.7

      - uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Terraform Init
        id: init
        run: terraform init -no-color -input=false -lock=true -get=true

      - name: Terraform Validate
        id: validate
        run: |
          terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform plan -detailed-exitcode
        continue-on-error: true

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: |
          echo "Drift detected on this terraform workspace"
          exit 1
